# -*- coding: utf-8 -*-
"""Tesselaton_Solution

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dpUaVcu6LrD4ECvgjVVR67WIirfH-7Zb
"""

test_str = "0134"
def evolve(shape):
  out = ""
  for item in shape:
    if int(item) in [0,1,3,4]:
      item = str( int(item)+1 )
    elif int(item) == 2:
      item="2344"
    elif int(item) == 5:
      item="1105"
    out = ''.join((out,item))
  return out

new_shape = "0134"
shape_list = [init_shape]
for idx in range(0,10):
  new_shape = evolve( new_shape )
  print(new_shape)
  shape_list.append(new_shape)

shape_list[2]

print(len(shape_list[2]))

