# -*- coding: utf-8 -*-
"""Tesselation_Solution

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dpUaVcu6LrD4ECvgjVVR67WIirfH-7Zb
"""

def evolve(shape,n,p,q,r):
  out = ""
  string_n = str(n)*p + '4'*r + '5'*q
  string_inv_n = '2'*q + '1'*r + str(2*n)*p
  for item in shape:
    if int(item) in [1,2,4,5]:
      item = str( int(item)+1 )
    elif int(item) == n:
      item = string_n
    elif int(item) == 2*n:
      item= string_inv_n
    out = ''.join((out,item))
  return out

new_shape = "1245"
p,q,r = 1,2,1
n=3
shape_list = [init_shape]
for idx in range(0,10):
  new_shape = evolve(new_shape,n,p,q,r)
  print(new_shape)
  shape_list.append(new_shape)

shape_list[2]

